//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhoneMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billdetail
    {
        public int bill_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> quanlity { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
    }
}
