//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhoneMobile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebPhoneMobileEntities : DbContext
    {
        public WebPhoneMobileEntities()
            : base("name=WebPhoneMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bill { get; set; }
        public virtual DbSet<billdetail> billdetail { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<product> product { get; set; }
    }
}
